In [1]:
#Cross validation: divide the sample into folds
#For eg. there's a 100 samples so you divide it into 5 folds. Take the first fold as a test sample and the rest as training sample. 
#Then second as test sample and the remaining four as traiing samples. Once we've done all of that till 5, we find the average score of all models

In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import numpy as np
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier


digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [5]:
lr= LogisticRegression()
lr.fit(X_train, Y_train)
lr.score(X_test, Y_test)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9481481481481482

In [7]:
svm = SVC()
svm.fit(X_train, Y_train)
svm.score(X_test, Y_test)

0.9814814814814815

In [60]:
rf = RandomForestClassifier(n_estimators=20)
rf.fit(X_train, Y_train)
rf.score(X_test, Y_test)

NameError: name 'RandomForestClassifier' is not defined

In [62]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf#specifying how many folds we want for our data set

KFold(n_splits=3, random_state=None, shuffle=False)

In [64]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]): #this data set is split into three foldsd
    print(train_index, test_index)  #first set is training array, the second testing array. The testing array is changed on each iteration

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [43]:
def get_score(model, X_train, X_test, Y_train, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test, Y_test)

In [66]:
get_score(LogisticRegression(), X_train, X_test, Y_train, Y_test)  #modularizing the code. We could've done this instead of writing 3 lines everytime for each algorithm we wanted

ValueError: Found input variables with inconsistent numbers of samples: [1198, 1257]

In [137]:
from sklearn.model_selection import StratifiedKFold #this is better bc it divides classificatiin categories in a unifrom way
folds = StratifiedKFold(n_splits=3)  

In [139]:
scores_l =[]
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]  #bc we've 3 folds, the for loop will reopeat 3 times.Measuring perormance of the model
    scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
    

In [84]:
#print(get_score(LogisticRegression(),  X_train, X_test, y_train, y_test))
#print(get_score(SVC(),  X_train, X_test, y_train, y_test))
#print(get_score(RandomForestClassifier(),  X_train, X_test, y_train, y_test))  
#instead of just printing, we'll appendd the scores

In [140]:
scores_l

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [143]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [145]:
scores_rf

[0.9365609348914858, 0.9432387312186978, 0.9315525876460768]

In [147]:
from sklearn.model_selection import cross_val_score

In [153]:
cross_val_score(LogisticRegression(), digits.data, digits.target, cv=3)  #this is essentially doing the same thing as or loop above

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92153589, 0.94156928, 0.91652755])

In [155]:
cross_val_score(SVC(), digits.data, digits.target, cv=3) 

array([0.96494157, 0.97996661, 0.96494157])

In [ ]:
cross_val_score(SVC(), digits.data, digits.target, cv=3) 